### PR TITLE
Add Crane Bird

### PR DESCRIPTION
**Pull request by perSimone**
Hello, I made this crane bird from a tutorial, gave it my own colours and love how it turned out. Hope this will work to upload it. Am pretty new to GitHub.

### CODE REVIEW

**Comment by xaca** [comment]
@perSimone Do you have to versions of same animal? This is a new animal? Tell me how to deal with this pull request. Thank you!

**Comment by perSimone** [comment]
Hey! Something went wrong, I thought the first one did not work. Maybe I was inpatient or did not look in the right place. If it is there twice, I can change it tomorrow, or can you delete one? They should be the same. Sorry!

**Comment by xaca** [comment]
@perSimone Ok, don't worry. I'm closing this pr. Thank you for clarification. :star2:

**Comment by xaca** [comment]
@perSimone Ok, don't worry. I'm closing this pr. Thank you for clarification. :star2:

**Pull request closed without merging**
