### PR TITLE
Created adorable owl

### PR DESCRIPTION
**Pull request by henriquehorbovyi**
I've created a cute owl to put in the zoo :owl:

### CODE REVIEW

**Comment by xaca** [comment]
@henrikhorbovyi :owl: :heart:  Nice! thank you!

**Comment by henriquehorbovyi** [comment]
@xaca Thank you. I'm an android developer, but I'm guiding my wife (@IraTeixeira) to enter in this world of programming as a FrontEnd developer :smile: . I'm really excited for her, cause she is learning a lot specially with Hacktoberfest and projects like this.

**Comment by xaca** [comment]
@henrikhorbovyi great, I remember your wife, she made good contributions. I'm glad booth participate on my projects. Thank you for your message. I love programming in general, nice to hear your expirience with hacktoberfest. I'm waiting to complete my four PR. How about you guys?

**Comment by henriquehorbovyi** [comment]
@xaca, I've completed 3, and she did it all already :sweat_smile:  She was really excited last weekend cause it's her first hacktoberfest and she couldn't sleep until finish all 4 PRs :smile:

**Comment by henriquehorbovyi** [comment]
Of course, my PR was a bit more complicated ahahahah... and now I'm looking for my last contribution

**Comment by xaca** [comment]
@xaca she beat you :smile: important has the passion, you are a good mentor to her. I have [c:heart:ding music](https://github.com/xaca/coding-music/issues) could you participate with some music from brazil? for your last PR.

**Comment by henriquehorbovyi** [comment]
I'm gonna check it out later, thank you

**Comment by xaca** [comment]
@henrikhorbovyi :+1:

**Pull request merged**
